# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Pradeep Kumar
tagline:          Smart Web Sites and Mobile Apps Architect with Cloud Backends
description:      Personal Development Blog for Pradeep Kumar
url:              http://getpoole.com

author:
  name:           Pradeep Kumar
  url:            https://twitter.com/pradeepkr103

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/pradeepkr103
